"""
Single source of truth for intentional data-quality issue counts.

Values mirror ``src/data_generation/generate_sample_data.py`` (seed=42).
"""

from __future__ import annotations

# Customer CSV / Silver expectations
NULL_EMAIL_COUNT = 50
DUPLICATE_CUSTOMER_ID_KEY_COUNT = 10
DUPLICATE_CUSTOMER_ROW_COUNT = DUPLICATE_CUSTOMER_ID_KEY_COUNT * 2  # all members flagged

CUSTOMER_TOTAL_COUNT = 10_000

# Order CSV / Silver expectations
NULL_CUSTOMER_ID_COUNT = 100
NULL_PRODUCT_ID_COUNT = 200
INVALID_CUSTOMER_ID_COUNT = 50
INVALID_PRODUCT_ID_COUNT = 30
DUPLICATE_ORDER_ID_KEY_COUNT = 20
DUPLICATE_ORDER_ROW_COUNT = DUPLICATE_ORDER_ID_KEY_COUNT * 2

ORDER_TOTAL_COUNT = 100_000
PRODUCT_TOTAL_COUNT = 500

DEFAULT_GENERATION_SEED = 42

# Rule IDs used for metric and row-level assertions
RULE_CUSTOMERS_EMAIL_NOT_NULL = "customers_email_not_null"
RULE_CUSTOMERS_CUSTOMER_ID_UNIQUE = "customers_customer_id_unique"
RULE_ORDERS_CUSTOMER_ID_NOT_NULL = "orders_customer_id_not_null"
RULE_ORDERS_PRODUCT_ID_NOT_NULL = "orders_product_id_not_null"
RULE_ORDERS_CUSTOMER_ID_EXISTS = "orders_customer_id_exists"
RULE_ORDERS_PRODUCT_ID_EXISTS = "orders_product_id_exists"
RULE_ORDERS_ORDER_ID_UNIQUE = "orders_order_id_unique"

INTENTIONAL_ISSUE_RULES = {
    RULE_CUSTOMERS_EMAIL_NOT_NULL: NULL_EMAIL_COUNT,
    RULE_CUSTOMERS_CUSTOMER_ID_UNIQUE: DUPLICATE_CUSTOMER_ROW_COUNT,
    RULE_ORDERS_CUSTOMER_ID_NOT_NULL: NULL_CUSTOMER_ID_COUNT,
    RULE_ORDERS_PRODUCT_ID_NOT_NULL: NULL_PRODUCT_ID_COUNT,
    RULE_ORDERS_CUSTOMER_ID_EXISTS: INVALID_CUSTOMER_ID_COUNT,
    RULE_ORDERS_PRODUCT_ID_EXISTS: INVALID_PRODUCT_ID_COUNT,
    RULE_ORDERS_ORDER_ID_UNIQUE: DUPLICATE_ORDER_ROW_COUNT,
}
